version: '3.8'

services:
  redis:
    image: redis:6.2.5-alpine
    container_name: stomp_study_redis
    restart: no
    command: redis-server --requirepass study
    volumes:
      - redis_data:/data
    ports:
      - "6407:6379"

volumes:
  redis_data:
